import pandas as pd 
data=pd.read_csv("C:/Users/HP/Desktop/penguins_lter.csv")
print(data)
print("PRINTING DISTINCT COLOUMN:")
a=data.get('Species',default="species")
print(a)
print("MEAN OF BODY MASS COLOUMN IS:")
print(data["Body Mass (g)"].mean())
print("MEDIAN OF BODYMASS COLOUMN IS:")
print(data["Body Mass (g)"].median())
print("MAX ELEMENT OF BODYMASS COLOUMN IS:")
print(data["Body Mass (g)"].max())
print("MINIMUM ELEMENT OF BODYMASS COLOUMN IS:")
print(data["Body Mass (g)"].min())
print("PRINTING RANDOM ROWS :")
print(data.sample())
