import pandas as pd
df=pd.read_csv("F:/CSV/Iris.csv",index_col="Id")
print(df)
print("PRINTING DISTINCT COLOUMN:")
a=df.get('SepalLengthCm',default="sepallength")
print(a)
print("MEAN OF SEPALLENGTH COLOUMN IS:")
print(df["SepalLengthCm"].mean())
print("MEDIAN OF SEPALLENGTH COLOUMN IS:")
print(df["SepalLengthCm"].median())
print("MAX ELEMENT OF SEPALLENGTH COLOUMN IS:")
print(df["SepalLengthCm"].max())
print("MINIMUM ELEMENT OF SEPALLENGTH COLOUMN IS:")
print(df["SepalLengthCm"].min())
print("PRINTING RANDOM ROWS :")
print(df.sample())
